-- =====================================================================
-- UC3 / Excalibur - Oracle source table structures
--
-- Source business columns only, exactly as specified in the UC3 DDL
-- sheets (BT_Usecase/UC3/data/*_DDL.csv). Generated with the framework's
-- own parser (src/uc3_simulator/uc3_ddl_schema.py) so these match the
-- Databricks side column-for-column and in the same order.
--
-- Applied from the sheets:
--   - a column exists iff 'Feed column name' is non-empty
--   - Drop(DF)=Y  -> column omitted (SUBSCRIBER: ctn_password, sub_password)
--   - Null(DF)=Y  -> column present and nullable
--   - hash_value / src_deleted_flg / gcp_* are NOT source columns and are
--     deliberately not created here
-- =====================================================================

-- ---------------------------------------------------------------------
-- PHYSICAL_DEVICE  -  31 columns
-- Primary key: customer_id, subscriber_no, equipment_no, phy_seq_no
-- Null(DF)=Y, nullable: esn_pin, blacklist_password
-- ---------------------------------------------------------------------
CREATE TABLE physical_device (
  customer_id                NUMBER(9,0)     NOT NULL,
  subscriber_no              CHAR(11)        NOT NULL,
  equipment_no               VARCHAR2(15)    NOT NULL,
  phy_seq_no                 NUMBER(9,0)     NOT NULL,
  sys_creation_date          DATE            NOT NULL,
  sys_update_date            DATE           ,
  operator_id                NUMBER(9,0)    ,
  application_id             CHAR(6)        ,
  dl_service_code            CHAR(5)        ,
  dl_update_stamp            NUMBER(4,0)    ,
  effective_date_time        DATE           ,
  expiration_date_time       DATE           ,
  equipment_ind              CHAR(1)        ,
  ownership_code             CHAR(2)        ,
  machine_serial_no          VARCHAR2(16)   ,
  change_reason_code         CHAR(1)        ,
  change_equip_actv          CHAR(3)        ,
  model_code                 CHAR(8)        ,
  lock_code                  CHAR(4)        ,
  esn_pin                    VARCHAR2(16)   ,
  conv_run_no                NUMBER(3,0)    ,
  blacklist_password         VARCHAR2(28)   ,
  upgrade_amt                NUMBER(11,2)   ,
  f_o_c_ind                  CHAR(1)        ,
  upgrade_type               CHAR(1)        ,
  max_foc_code               VARCHAR2(4)    ,
  retention_offer_id         NUMBER(9,0)    ,
  wrh_order_no               VARCHAR2(10)   ,
  dealer_code                CHAR(8)        ,
  chg_created_ind            CHAR(2)        ,
  dvc_unlock_chgdate         DATE           ,
  CONSTRAINT pk_physical_device PRIMARY KEY (customer_id, subscriber_no, equipment_no, phy_seq_no)
);

-- ---------------------------------------------------------------------
-- CUSTOMER  -  90 columns
-- Primary key: customer_id
-- Null(DF)=Y, nullable: gur_cr_card_no, acc_password, imei_black_list_pass
-- ---------------------------------------------------------------------
CREATE TABLE customer (
  customer_id                NUMBER(9,0)     NOT NULL,
  sys_creation_date          DATE            NOT NULL,
  sys_update_date            DATE           ,
  operator_id                NUMBER(9,0)    ,
  application_id             CHAR(6)        ,
  dl_service_code            CHAR(5)        ,
  dl_update_stamp            NUMBER(4,0)    ,
  contact_telno              CHAR(11)       ,
  contact_tn_extno           NUMBER(4,0)    ,
  contact_faxno              CHAR(11)       ,
  contact_country_code       CHAR(3)        ,
  work_telno                 CHAR(11)       ,
  work_tn_extno              NUMBER(4,0)    ,
  home_telno                 CHAR(11)       ,
  other_telno                CHAR(11)       ,
  other_extno                NUMBER(4,0)    ,
  other_tn_type              VARCHAR2(15)   ,
  birth_date                 DATE           ,
  employment_dt              CHAR(6)        ,
  emplyr_name                VARCHAR2(60)   ,
  employee_qty               CHAR(2)        ,
  years_in_business          NUMBER(3,0)    ,
  employee_position          VARCHAR2(25)   ,
  business_est_date          DATE           ,
  market_id                  CHAR(3)        ,
  gur_cr_card_type           CHAR(2)        ,
  gur_cr_card_no             CHAR(21)       ,
  gur_cr_card_exp_dt         DATE           ,
  acc_password               VARCHAR2(28)   ,
  verified_date              DATE           ,
  company_register_num       VARCHAR2(16)   ,
  business_category          NUMBER(5,0)    ,
  conv_run_no                NUMBER(3,0)    ,
  legacy_cst_num             NUMBER(8,0)    ,
  e_mail_addr                VARCHAR2(50)   ,
  mailshot                   CHAR(10)       ,
  imei_black_list_pass       VARCHAR2(6)    ,
  company_type               CHAR(1)        ,
  cust_gender                CHAR(1)        ,
  cust_personal_id           VARCHAR2(16)   ,
  cust_nationality           CHAR(3)        ,
  autprsn_birth_date         DATE           ,
  autprsn_personal_id        VARCHAR2(16)   ,
  guarantor_type             CHAR(1)        ,
  gur_personal_id            VARCHAR2(16)   ,
  gur_company_reg_num        VARCHAR2(16)   ,
  start_time_at_bank         DATE           ,
  gur_birth_date             DATE           ,
  gur_tax_number             VARCHAR2(16)   ,
  register_ind               CHAR(1)        ,
  contact_telno_2nd          CHAR(11)       ,
  contact_tn_extno_2nd       NUMBER(4,0)    ,
  contact_faxno_2nd          CHAR(11)       ,
  contact_country_code_2nd   CHAR(3)        ,
  credit_card_ind            CHAR(1)        ,
  authorized_sec             CHAR(8)        ,
  etu_count                  NUMBER(4,0)    ,
  contact_email_address      VARCHAR2(50)   ,
  contact_department         VARCHAR2(50)   ,
  contact_job_description    VARCHAR2(50)   ,
  bac_cust_support_team      CHAR(5)        ,
  bac_territory_code         CHAR(5)        ,
  external_id                VARCHAR2(100)  ,
  open_date                  DATE           ,
  customer_type              CHAR(3)        ,
  assistant_user_id          NUMBER(9,0)    ,
  marketing_channel          VARCHAR2(4)    ,
  ch_node_id                 NUMBER(10,0)   ,
  lock_customer_ind          CHAR(1)        ,
  resource_pool              VARCHAR2(5)    ,
  spc_memo_ind               CHAR(1)        ,
  bill_cycle                 NUMBER(2,0)    ,
  bill_cyc_prod_freq         NUMBER(2,0)    ,
  change_cycle_ind           CHAR(1)        ,
  chg_cycle_req_sts          CHAR(1)        ,
  new_cycle                  NUMBER(2,0)    ,
  new_cyc_prod_freq          NUMBER(2,0)    ,
  tax_exempt_int             CHAR(1)        ,
  tax_exempt_date            DATE           ,
  hierarchy_policy           VARCHAR2(4)    ,
  credit_class               CHAR(1)        ,
  cust_sub_type              VARCHAR2(4)    ,
  dflt_pre_pcn               NUMBER(9,0)    ,
  dflt_post_pcn              NUMBER(9,0)    ,
  legacy_cust_no             NUMBER(9,0)    ,
  dealer_code                CHAR(8)        ,
  cust_desc_cd               CHAR(3)        ,
  charity_reg_num            CHAR(10)       ,
  no_email_reason            CHAR(4)        ,
  hint_id                    NUMBER(9,0)    ,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

-- ---------------------------------------------------------------------
-- SUBSCRIBER  -  131 columns
-- Primary key: subscriber_no, customer_id
-- Drop(DF)=Y, not created: ctn_password, sub_password
-- ---------------------------------------------------------------------
CREATE TABLE subscriber (
  subscriber_no              CHAR(11)        NOT NULL,
  customer_id                NUMBER(9,0)     NOT NULL,
  sys_creation_date          DATE            NOT NULL,
  sys_update_date            DATE           ,
  operator_id                NUMBER(9,0)    ,
  application_id             CHAR(6)        ,
  dl_service_code            CHAR(5)        ,
  dl_update_stamp            NUMBER(4,0)    ,
  effective_date             DATE            NOT NULL,
  init_activation_date       DATE           ,
  sub_status                 CHAR(1)         NOT NULL,
  sub_status_date            DATE            NOT NULL,
  sub_status_last_act        CHAR(3)        ,
  sub_status_rsn_code        CHAR(4)        ,
  customer_ban               NUMBER(9,0)    ,
  commit_start_date          DATE           ,
  commit_end_date            DATE           ,
  commit_reason_code         CHAR(3)        ,
  commit_orig_no_month       NUMBER(3,0)    ,
  susp_rc_rate_type          CHAR(1)        ,
  req_deposit_amt            NUMBER(13,2)   ,
  allocation_code_1          VARCHAR2(10)   ,
  allocation_code_2          VARCHAR2(10)   ,
  activation_method          CHAR(1)        ,
  last_actv_code             CHAR(3)        ,
  last_actv_reason           CHAR(5)        ,
  last_actv_date             DATE           ,
  ttn                        CHAR(11)       ,
  ttn_ind                    CHAR(1)        ,
  next_ctn                   CHAR(11)       ,
  next_ctn_chg_date          DATE           ,
  prv_ctn                    CHAR(11)       ,
  prv_ctn_chg_date           DATE           ,
  next_ban                   NUMBER(9,0)    ,
  next_ban_move_date         DATE           ,
  prv_ban                    NUMBER(9,0)    ,
  prv_ban_move_date          DATE           ,
  conv_run_no                NUMBER(3,0)    ,
  default_uc_ben             NUMBER(5,0)    ,
  default_oc_ben             NUMBER(5,0)    ,
  default_rc_ben             NUMBER(5,0)    ,
  rc_ben_level_code          CHAR(1)        ,
  vin                        VARCHAR2(30)   ,
  car_registration           VARCHAR2(30)   ,
  subscriber_ref             VARCHAR2(30)   ,
  np_code                    CHAR(1)         NOT NULL,
  product_code               CHAR(4)        ,
  arrangment                 CHAR(4)        ,
  sub_customer_value         CHAR(2)        ,
  dir_publish_ind            CHAR(1)        ,
  threshold_class            CHAR(2)        ,
  pre_payment_ind            CHAR(1)        ,
  pre_active_ind             CHAR(1)        ,
  manual_upgrade_amt         NUMBER(11,2)   ,
  manual_upgrade_given_date  DATE           ,
  manual_upgrade_last_date   DATE           ,
  partner_ind                CHAR(1)        ,
  max_partners               NUMBER(9,0)    ,
  f_o_c_ind                  CHAR(1)        ,
  crefit_limit_prim_ind      CHAR(1)        ,
  prec_upgrade               CHAR(1)        ,
  next_coupon_actv_date      DATE           ,
  next_coupon_policy_code    CHAR(2)        ,
  next_coupon_policy_step    NUMBER(2,0)    ,
  interlock_code             NUMBER(5,0)    ,
  pstn                       VARCHAR2(20)   ,
  tenure_date_prec           DATE           ,
  tenure_date_euro           DATE           ,
  dual_sim_link_ind          CHAR(1)        ,
  pcli                       CHAR(11)       ,
  disability_code            CHAR(4)        ,
  max_foc_code               VARCHAR2(4)    ,
  foc_upgrade_status         CHAR(1)        ,
  foc_tenure_date            DATE           ,
  enforce_restriction        CHAR(1)        ,
  enforce_restr_exp_date     DATE           ,
  waive_restriction          CHAR(1)        ,
  waive_restr_exp_date       DATE           ,
  handset_option             CHAR(1)        ,
  rc_level                   CHAR(1)        ,
  threshold_amount           NUMBER(11,2)   ,
  sub_seq_no                 NUMBER(9,0)    ,
  external_id                VARCHAR2(100)  ,
  ext_parent_id              VARCHAR2(100)  ,
  ch_node_id                 NUMBER(10,0)   ,
  sub_sts_issue_date         DATE           ,
  dealer_code                CHAR(8)        ,
  initial_dlr_code           CHAR(8)        ,
  subscriber_type            VARCHAR2(4)    ,
  act_waive_rsn_cd           CHAR(5)        ,
  earliest_actv_date         DATE           ,
  change_pp_cnt              NUMBER(9,0)    ,
  formal_cancel_date         DATE           ,
  retention_code             VARCHAR2(3)    ,
  prim_resource_tp           VARCHAR2(4)    ,
  prim_res_param_cd          VARCHAR2(25)   ,
  prim_resource_val          VARCHAR2(30)   ,
  calc_pym_category          VARCHAR2(4)    ,
  retention_start_dt         DATE           ,
  init_act_date              DATE           ,
  sub_sts_last_act           VARCHAR2(25)   ,
  sub_sts_rsn_cd             CHAR(5)        ,
  subscr_seq_no              NUMBER(9,0)    ,
  dd_amount                  NUMBER(11,2)   ,
  dd_pp_status               CHAR(1)        ,
  dd_prepay_ind              CHAR(1)        ,
  dd_pp_due_date             DATE           ,
  dd_pp_bill_seq_no          NUMBER(3,0)    ,
  payment_combination        CHAR(1)        ,
  pre_notify_type            CHAR(1)        ,
  sub_email                  VARCHAR2(50)   ,
  multi_sim_master           VARCHAR2(11)   ,
  multi_sim_sec_num          VARCHAR2(11)   ,
  bundle_group               NUMBER(9,0)    ,
  cntr_ext_non_upg           DATE           ,
  retention_offer_id         NUMBER(9,0)    ,
  to_nonupg_end_date         DATE           ,
  to_upg_end_date            DATE           ,
  no_downward_end_date       DATE           ,
  minimal_rc                 NUMBER(11,2)   ,
  family_role                CHAR(1)        ,
  lifetime_id                NUMBER(12,0)   ,
  pcc_id                     VARCHAR2(19)   ,
  pcc_email                  VARCHAR2(50)   ,
  source_brand               CHAR(1)        ,
  source_ban                 NUMBER(9,0)    ,
  start_service_date         DATE           ,
  exchg_eqp_restrict_ind     CHAR(1)        ,
  pp_type                    CHAR(4)        ,
  contract_ind               CHAR(5)        ,
  price_rise_segment         CHAR(1)        ,
  CONSTRAINT pk_subscriber PRIMARY KEY (subscriber_no, customer_id)
);
