"""
Comprehensive test suite verifying all features requested:
  1. All 4 flow tabs: Ingestion, Transformation, Reconciliation, Observability
  2. Exact canonical attributes matching pipeline_onboarding_template.json
  3. Live JSON/YAML render and serialization
  4. Saving to local, Databricks Workspace, and Unity Catalog Volume
  5. Repeatable items (encrypted_columns, rules, column_tags, source_inputs, decrypted_columns, target_configs, observability)
  6. KV pair mappings (spark_config, pipeline_parameters, reader_options, table_properties, tags, credentials)
  7. CDC strategies (APPEND, TRUNCATE_AND_LOAD, SCD1, SCD2, SCD3, FULL_SNAPSHOT_CDC)
  8. v1.4.0 removals are actually GONE from the shipped bundle, not merely unused
"""
import os
import json
import yaml
from fastapi.testclient import TestClient
import pytest

os.environ["METAFLOW_FAKE_DBX"] = "1"

from server.app import app

client = TestClient(app)


def test_v140_removed_attributes_are_absent_from_the_shipped_frontend(frontend_text):
    """The builder must not offer a field the framework rejects.

    This asserts on the BUILT bundle, not the source registry, because that is the gap this test
    closes: `web/dist/` is committed Vite output and is only regenerated by `npm run build`. Edit
    registry.js, forget the rebuild, and the app keeps serving the old form -- authors keep filling
    in `generate_surrogate_key`, and every spec they produce now fails onboarding validation with
    an error about an attribute the UI told them to set.
    """
    html = frontend_text
    for removed in (
        "generate_surrogate_key",
        "surrogate_key_columns",
        "surrogate_key_exclude_columns",
        "recon_mode",
        "normalize_column_names",
        "FULL_SNAPSHOT_CDC_NO_PK",
    ):
        assert removed not in html, (
            f"{removed} is still in the shipped frontend bundle -- run `npm run build` in "
            "databricks-app/web after changing registry.js or Builder.jsx"
        )


def test_spa_html_contains_all_flow_tabs(frontend_text):
    """Verify the shipped frontend contains Ingestion, Transformation, Reconciliation, Observability tabs."""
    html = frontend_text
    assert "Ingestion" in html
    assert "Transformation" in html
    assert "Reconciliation" in html
    assert "Observability" in html
    assert "Spec root" in html
    assert "Index" in html
    assert "Docs" in html


def test_spa_html_contains_all_canonical_attributes(frontend_text):
    """Verify all 150+ canonical attribute paths are defined in the shipped frontend."""
    html = frontend_text

    # Root attributes
    assert "dataflow_group_id" in html
    assert "pipeline_parameters" in html
    assert "spark_config" in html

    # Ingestion flow attributes
    assert "dataflow_id" in html
    assert "source_system" in html
    assert "source_database" in html
    assert "source_table_name" in html
    assert "source_description" in html
    assert "source_type" in html
    assert "target_catalog" in html
    assert "target_schema" in html
    assert "target_table" in html
    assert "target_type" in html
    assert "source_config.path" in html
    assert "source_config.format" in html
    assert "source_config.file_pattern" in html
    assert "source_config.schema_location" in html
    assert "source_config.schema_evolution_mode" in html
    assert "source_config.reader_options" in html
    assert "source_config.data_standardization_sql" in html
    assert "source_config.landing_retention_policy" in html
    assert "source_config.source_zip_handling" in html
    assert "source_config.column_normalization" in html
    assert "target_config.cdc_load_strategy" in html
    assert "target_config.primary_keys" in html
    assert "target_config.sequence_by_column" in html
    assert "target_config.columns_to_check" in html
    assert "target_config.columns_to_exclude" in html
    assert "target_config.cdc_operation_column" in html
    assert "target_config.cdc_operation_mapping" in html
    assert "target_config.generate_hash_columns" in html
    assert "target_config.encrypted_columns" in html
    assert "source_data_type" in html
    assert "target_config.sink_config" in html
    assert "dq_config.rules" in html
    assert "governance_tags.column_tags" in html
    assert "governance_tags.table_tags" in html

    # Transformation flow attributes
    assert "flow_step_id" in html
    assert "source_inputs" in html
    assert "decrypted_columns" in html
    assert "transformation_sql" in html

    # Reconciliation flow attributes
    assert "reconciliation_id" in html
    assert "two_tier_verification" in html
    assert "target_configs" in html
    assert "match_keys" in html
    assert "compare_columns" in html
    assert "transform_sql" in html

    # Observability attributes
    assert "observability" in html
    assert "DATABRICKS_VOLUME" in html
    assert "OTLP_CONSUMER" in html
    assert "destination_config.endpoint" in html


def test_spa_has_preloaded_template_data(frontend_text):
    """Verify the frontend ships the canonical sample identifiers used by its presets.

    The React builder starts from an empty spec and offers these as presets, rather
    than preloading one canonical spec the way the previous SPA did; the identifiers
    themselves are still shipped and must stay in step with the template catalogue.
    """
    html = frontend_text
    assert "dfg_finance_txn_ingest" in html
    assert "df_template_ingest" in html
    assert "df_template_zerobus_ingest" in html
    assert "df_template_asn1_ingest" in html
    assert "df_template_json_ingest" in html
    assert "ts_template_append_example" in html
    assert "ts_template_scd1_example" in html
    assert "ts_template_scd2_example" in html
    assert "recon_template_example" in html
    assert "dest-otlp-example" in html


def test_spec_router_roundtrip_canonical():
    """Verify spec_router renders and imports canonical template without data loss."""
    canonical_path = os.path.join(
        os.path.dirname(__file__), "..", "templates", "pipeline_onboarding_template.json"
    )
    with open(canonical_path, "r", encoding="utf-8") as f:
        original = json.load(f)

    # 1. Render to JSON
    res = client.post("/api/spec/render", json={"spec": original, "format": "json"})
    assert res.status_code == 200
    rendered_json = res.json()["content"]
    assert "dfg_template_example" in rendered_json
    assert "df_template_ingest" in rendered_json

    # 2. Render to YAML
    res = client.post("/api/spec/render", json={"spec": original, "format": "yaml"})
    assert res.status_code == 200
    rendered_yaml = res.json()["content"]
    assert "dfg_template_example" in rendered_yaml

    # 3. Import back
    res = client.post("/api/spec/import", json={"content": rendered_json, "format": "json"})
    assert res.status_code == 200
    imported = res.json()["spec"]
    assert "root" in imported or "dataflow_group_id" in imported


def test_save_destinations_api():
    """Verify save endpoints for local, workspace, and volume paths."""
    # 1. Workspace Save
    res1 = client.post("/api/workspace/write", json={
        "root_id": "ws_specs",
        "path": "/Workspace/Shared/metaflow/specs/pipeline_spec.json",
        "content": '{"$schema": "./onboarding_spec.schema.json", "dataflow_group_id": "dfg_test"}',
        "overwrite": True
    })
    assert res1.status_code in (200, 500)

    # 2. Volume Save
    res2 = client.post("/api/workspace/write", json={
        "root_id": "vol_specs",
        "path": "/Volumes/metaflow/metaflow/onboarding_specs/pipeline_spec.json",
        "content": '{"$schema": "./onboarding_spec.schema.json", "dataflow_group_id": "dfg_test"}',
        "overwrite": True
    })
    assert res2.status_code in (200, 500)


def test_docs_site_serves_whole_wiki():
    """/docs is the full framework wiki, not just the attribute reference.

    One page per audience journey has to be reachable — architecture, the FAQs,
    the generated JSON and code references, and the archive — otherwise the app
    is shipping onboarding docs only.
    """
    assert client.get("/docs/").status_code == 200

    for page in [
        "01_platform_architecture",          # architecture
        "faq",                               # help
        "10_multi_role_faqs",                # functional / per-role
        "13_known_limitations_and_gotchas",  # gotchas
        "onboarding",                        # get started
        "reference/json/ingestion",          # generated JSON reference
        "reference/code/engine",             # generated code reference
        "architecture_review/00_executive_summary",
        "archive",                           # superseded material, labelled
    ]:
        res = client.get(f"/docs/{page}/")
        assert res.status_code == 200, f"/docs/{page}/ -> {res.status_code}"

    # Full-text search over the whole wiki, not per-page anchors.
    assert client.get("/docs/search/search_index.json").status_code == 200

