# Databricks notebook source
# MAGIC %md
# MAGIC # Seed TC-CDC-007 -- Full Snapshot Diffing Without PK Fixtures
# MAGIC
# MAGIC Dedicated seed notebook for `metaflow_testing/025_cdc_007_snapshot_nopk.json` only --
# MAGIC intentionally separate from `02_seed_metaflow_testing_data.py` and every other scenario's
# MAGIC own seed notebook, so this test case's build/run stays isolated.
# MAGIC
# MAGIC Provisions the `legacy` schema and `landing_mainframe`/`_schemas` Volumes, then lands
# MAGIC **only** the Day-1 mainframe extract (`sample_mainframe_customer_master_day1.csv`, 10
# MAGIC rows, no natural key column at all) in the landing Volume. This job's own pipeline run
# MAGIC therefore only ever sees the Day-1 full snapshot -- the Day-2 extract
# MAGIC (`sample_mainframe_customer_master_day2.csv`: `John Smith` status changed, `Fatima Ali`
# MAGIC city changed, `Wei Zhang` removed, `Noah Kim` added) is deliberately **not** landed by
# MAGIC this notebook; it is copied in manually as a second step, per `docs/46_tc_cdc_007.md`, to
# MAGIC prove `__framework_surrogate_key`-based insert/update/delete diffing across two separate
# MAGIC pipeline updates.
# MAGIC
# MAGIC Reuses the existing top-level `sample_data/sample_mainframe_customer_master_day1.csv`/
# MAGIC `_day2.csv` fixtures (already generated by
# MAGIC `sample_data/generate_sample_datasets.py::generate_mainframe_snapshot_datasets`) rather than
# MAGIC authoring new ones -- their shape (no primary key column, one update/one delete/one insert
# MAGIC between Day-1 and Day-2) is exactly what this scenario needs.
# MAGIC
# MAGIC Run once per environment before onboarding `metaflow_testing/025_cdc_007_snapshot_nopk.json`.

# COMMAND ----------

import logging
import os

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("seed_cdc_007_snapshot_nopk_data")

dbutils.widgets.text("catalog", "metaflow", "Target Unity Catalog")
CATALOG = dbutils.widgets.get("catalog").strip()

if not CATALOG:
    raise ValueError("The 'catalog' widget must be set to a valid Unity Catalog name.")

_this_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
REPO_ROOT = os.path.abspath(os.path.join(_this_dir, "..", ".."))
FIXTURE_DIR = os.path.join(REPO_ROOT, "sample_data")

if not os.path.isdir(FIXTURE_DIR):
    raise FileNotFoundError(f"Expected fixture directory at '{FIXTURE_DIR}' -- is sample_data/ synced alongside this notebook?")

logger.info("Resolved sample_data fixture directory: %s", FIXTURE_DIR)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Provision Schemas & Volumes
# MAGIC
# MAGIC `legacy` hosts the landing Volume; `silver_legacy` (the FULL_SNAPSHOT_CDC_NO_PK target
# MAGIC schema) is created automatically by the pipeline's own `CREATE SCHEMA IF NOT EXISTS` at
# MAGIC deployment time, same as every other scenario -- no need to pre-create it here.

# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.legacy")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {CATALOG}.legacy.landing_mainframe")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {CATALOG}.legacy._schemas")

logger.info("Provisioned catalog '%s' with legacy schema + landing_mainframe/_schemas volumes.", CATALOG)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Land Day-1 Mainframe Extract Only

# COMMAND ----------

LEGACY_LANDING_ZONE = f"/Volumes/{CATALOG}/legacy/landing_mainframe"
dbutils.fs.mkdirs(LEGACY_LANDING_ZONE)

_day1_fixture = os.path.join(FIXTURE_DIR, "sample_mainframe_customer_master_day1.csv")
if not os.path.exists(_day1_fixture):
    raise FileNotFoundError(f"Required Day-1 mainframe fixture missing: '{_day1_fixture}'")

dbutils.fs.cp(f"file:{_day1_fixture}", f"{LEGACY_LANDING_ZONE}/sample_mainframe_customer_master_day1.csv")
logger.info(
    "Landed Day-1 mainframe extract at '%s/sample_mainframe_customer_master_day1.csv' (10 rows, no natural key).",
    LEGACY_LANDING_ZONE,
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Done
# MAGIC
# MAGIC `metaflow_testing/025_cdc_007_snapshot_nopk.json` can now be onboarded and its pipeline run
# MAGIC for the Day-1 baseline (10 rows, every row getting a `__framework_surrogate_key`). See
# MAGIC `docs/46_tc_cdc_007.md` for the manual Day-2 step (copying
# MAGIC `sample_mainframe_customer_master_day2.csv` into this same landing Volume and re-running
# MAGIC the pipeline) that this notebook deliberately does not automate.
# MAGIC
# MAGIC Re-running this notebook on its own is safe and idempotent: it only ever re-copies the
# MAGIC Day-1 file (Auto Loader tracks already-ingested files via its own checkpoint, so
# MAGIC re-landing the same filename does not re-ingest or duplicate rows), and it never touches
# MAGIC or removes a Day-2 file a tester may have already copied in separately.
