"""The agent-facing golden specs must always validate (v1.7.1).

``agent_skills/reference/golden_specs.json`` is what a generating agent copies from. A stale
example there is worse than no example: it teaches the exact attribute names the validator now
rejects, which is the failure this whole change exists to remove. These specs are generated by
``scripts/build_golden_specs.py`` (which validates before writing); this test is the standing
guard that keeps them true as the spec evolves.
"""

import json

import pytest

from flowx.lakeflow_framework.onboarding.spec_validator import validate_spec

GOLDEN_PATH = "agent_skills/reference/golden_specs.json"


def _golden():
    with open(GOLDEN_PATH, encoding="utf-8") as handle:
        return json.load(handle)


def _payload(spec):
    """Strip the ``_use_when`` narration; everything else is the real spec."""
    return {k: v for k, v in spec.items() if not k.startswith("_")}


def test_golden_file_is_non_empty():
    assert len(_golden()) >= 5


@pytest.mark.parametrize("name", sorted(_golden()))
def test_golden_spec_validates_clean(name):
    *_, errors = validate_spec(None, _payload(_golden()[name]))
    assert errors == [], f"{name}: {errors}"


@pytest.mark.parametrize("name", sorted(_golden()))
def test_golden_spec_explains_when_to_use_it(name):
    """Each example must say what it is for -- an unlabelled example gets copied at random."""
    assert _golden()[name].get("_use_when", "").strip()


@pytest.mark.parametrize("name", sorted(_golden()))
def test_golden_spec_declares_at_least_one_flow_array(name):
    payload = _payload(_golden()[name])
    assert any(
        payload.get(key) for key in ("ingestion_flows", "transformation_flows", "reconciliation_flows")
    ), name


def test_golden_specs_cover_the_main_shapes():
    """Coverage guard: the set must keep spanning the shapes agents actually get wrong."""
    blob = json.dumps(_golden())
    for token in ("autoloader", "zerobus", "SCD1", "SCD2", "dq_config", "governance_tags",
                  "transformation_flows", "reconciliation_flows", "source_inputs"):
        assert token in blob, f"golden specs no longer cover {token}"
