"""Unit tests for archive/zip_ingestion_pipeline.py::validate_zip_batch -- pure Python,
no Spark needed (validation is plain filesystem + zipfile logic)."""

import os
import zipfile
from pathlib import Path

import pytest

from flowx.lakeflow_framework.exceptions import ArchiveError
from flowx.lakeflow_framework.archive.zip_ingestion_pipeline import validate_zip_batch

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURES_DIR = REPO_ROOT / "sample_data" / "zip_ingestion"


def _make_valid_zip(path: str, member_name: str = "data.csv", content: str = "a,b\n1,2\n") -> str:
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr(member_name, content)
    return path


def test_valid_batch_passes(tmp_path):
    # Distinct content per file -- otherwise these would be genuine byte-identical
    # duplicates, which validate_zip_batch is correctly supposed to reject (see
    # test_duplicate_content_across_two_names_is_reported below).
    paths = [
        str(_make_valid_zip(str(tmp_path / f"valid_{i}.zip"), content=f"distinct content {i}\n")) for i in range(4)
    ]
    validate_zip_batch(paths)  # should not raise


def test_missing_file_is_reported(tmp_path):
    valid = str(_make_valid_zip(str(tmp_path / "valid.zip")))
    missing = str(tmp_path / "does_not_exist.zip")
    with pytest.raises(ArchiveError, match="missing.*does_not_exist"):
        validate_zip_batch([valid, missing])


def test_empty_file_is_reported(tmp_path):
    empty_path = tmp_path / "empty.zip"
    empty_path.write_bytes(b"")
    with pytest.raises(ArchiveError, match="empty"):
        validate_zip_batch([str(empty_path)])


def test_malformed_zip_is_reported(tmp_path):
    malformed_path = tmp_path / "malformed.zip"
    malformed_path.write_bytes(b"not a real zip file")
    with pytest.raises(ArchiveError, match="malformed"):
        validate_zip_batch([str(malformed_path)])


def test_zip_with_no_members_is_reported(tmp_path):
    no_members_path = tmp_path / "no_members.zip"
    with zipfile.ZipFile(str(no_members_path), "w"):
        pass
    with pytest.raises(ArchiveError, match="empty.*no members"):
        validate_zip_batch([str(no_members_path)])


def test_duplicate_content_across_two_names_is_reported(tmp_path):
    original = str(_make_valid_zip(str(tmp_path / "original.zip")))
    duplicate_path = tmp_path / "duplicate.zip"
    duplicate_path.write_bytes(open(original, "rb").read())
    with pytest.raises(ArchiveError, match="duplicate"):
        validate_zip_batch([original, str(duplicate_path)])


def test_multiple_problems_are_all_reported_together(tmp_path):
    missing = str(tmp_path / "missing.zip")
    empty_path = tmp_path / "empty.zip"
    empty_path.write_bytes(b"")
    malformed_path = tmp_path / "malformed.zip"
    malformed_path.write_bytes(b"garbage")

    with pytest.raises(ArchiveError) as exc_info:
        validate_zip_batch([missing, str(empty_path), str(malformed_path)])
    message = str(exc_info.value)
    assert "missing" in message
    assert "empty" in message
    assert "malformed" in message


def test_distinct_valid_archives_are_not_flagged_as_duplicates(tmp_path):
    a = str(_make_valid_zip(str(tmp_path / "a.zip"), content="different content a\n"))
    b = str(_make_valid_zip(str(tmp_path / "b.zip"), content="different content b\n"))
    validate_zip_batch([a, b])  # should not raise


# --- Tests against the real generated fixtures under sample_data/zip_ingestion/ ---
# (generated by sample_data/generate_zip_ingestion_fixtures.py) -- proves the actual
# sample data behaves the way docs/12_zip_ingestion_pipeline.md describes, not just a
# synthetic tmp_path stand-in.


def _require_fixtures():
    if not FIXTURES_DIR.is_dir():
        pytest.skip(
            f"{FIXTURES_DIR} not found -- run 'python sample_data/generate_zip_ingestion_fixtures.py' first"
        )


def test_real_four_zip_batch_is_valid():
    _require_fixtures()
    valid_batch = [
        str(FIXTURES_DIR / name)
        for name in ("zip_sales_branch_east.zip", "zip_sales_branch_west.zip", "zip_ref_customers.zip", "zip_ref_products.zip")
    ]
    validate_zip_batch(valid_batch)  # should not raise


def test_real_malformed_fixture_is_rejected():
    _require_fixtures()
    with pytest.raises(ArchiveError, match="malformed"):
        validate_zip_batch([str(FIXTURES_DIR / "zip_malformed.zip")])


def test_real_duplicate_fixture_is_rejected():
    _require_fixtures()
    with pytest.raises(ArchiveError, match="duplicate"):
        validate_zip_batch(
            [str(FIXTURES_DIR / "zip_sales_branch_east.zip"), str(FIXTURES_DIR / "zip_sales_branch_east_duplicate.zip")]
        )


def test_real_empty_zip_fixture_is_rejected():
    _require_fixtures()
    with pytest.raises(ArchiveError, match="empty"):
        validate_zip_batch([str(FIXTURES_DIR / "zip_empty.zip")])
